# Generated by Django 5.1.5 on 2025-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crastatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporatename', models.CharField(max_length=250)),
                ('proxyid', models.IntegerField(null=True)),
                ('entityid', models.CharField(max_length=128)),
                ('programname', models.CharField(max_length=128, null=True)),
                ('programstatus', models.CharField(max_length=128, null=True)),
                ('evaluationfactdi', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
