# Generated by Django 5.1.5 on 2025-02-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crastatus',
            name='createdate',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='crastatus',
            name='updatedate',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
