# Generated by Django 5.1.5 on 2025-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_crastatus_createdate_crastatus_updatedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraFtpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=250)),
                ('records', models.IntegerField(null=True)),
            ],
        ),
    ]
