# Generated by Django 5.1.5 on 2025-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_craftplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programname', models.CharField(max_length=128)),
                ('sequence', models.IntegerField()),
            ],
        ),
    ]
