# Generated by Django 5.1.5 on 2025-01-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_block_1', models.CharField(max_length=80)),
                ('purchase_block_2', models.CharField(max_length=80)),
                ('payment_block_3', models.CharField(max_length=80)),
                ('payment_block_type', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupa_supplier_id', models.IntegerField(null=True)),
                ('coupa_sim_id', models.IntegerField(null=True)),
                ('system_id_1', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.company')),
            ],
        ),
        migrations.CreateModel(
            name='compliance_threshhold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity', models.CharField(max_length=80, null=True)),
                ('total_year', models.CharField(max_length=4, null=True)),
                ('spend_non_po_invoices', models.FloatField(null=True)),
                ('spend_purchase_orders', models.FloatField(null=True)),
                ('spend_total', models.FloatField(null=True)),
                ('spend_threshold', models.FloatField(null=True)),
                ('spend_currency', models.CharField(max_length=4, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
